Project refactor
Berkay-akbas/Awesome-Books pull request #2
Opened 2022-06-28 12:43 UTC by alanluqman

## Description 📄 
> In this pull request, I and my partner worked on this project and added a style, and used class to collect data.

## File Changed ♻️ 
- style.css
- index.html
- script.js

2022-06-28 19:00 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @alanluqman and @Berkay-akbas,

Good job so far!
✔️ Use of classes
✔️ Books can be added and removed
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly format your entire README to follow the [Microverse template](https://github.com/microverseinc/readme-template)

  ![bag](https://user-images.githubusercontent.com/36542986/176261396-1cb821a8-19a7-4006-8eb5-db04b94d7917.jpg)

- [x] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 19:00 UTC, TedLivist commented on app.js
> +// }
- [ ] Kindly remove commented code here. It makes your codebase look messy and can be confusing.

2022-06-28 19:00 UTC, TedLivist commented on app.js
> +  // console.log(library);
- [ ] Kindly remove commented code here.

2022-06-29 08:02 UTC, gemmen29 approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
- [ ] Kindly add some instructions in your README file on how to clone the project and run it locally to make your README more professional.
- [ ] Please clear the inputs of `Title` and `Author` after adding a book for a better user experience.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 08:07 UTC, merged